// GrpcTransport — gRPC transport adapter
// Auto-generates .proto from EntitySchemas and serves gRPC
// Author: Dr Hamid MADANI drmdh@msn.com

import type { EntitySchema, OrmRequest, OrmResponse } from '@mostajs/orm';
import type { ITransport, TransportConfig, TransportInfo, TransportMiddleware, TransportContext } from '../core/types.js';

type OrmHandler = (req: OrmRequest, ctx: TransportContext) => Promise<OrmResponse>;

// Field type mapping: ORM → protobuf
const PROTO_TYPES: Record<string, string> = {
  string: 'string',
  number: 'double',
  boolean: 'bool',
  date: 'string', // ISO string
  objectId: 'string',
  json: 'string', // JSON string
  array: 'string', // JSON string
  text: 'string',
  integer: 'int64',
  float: 'double',
  decimal: 'double',
  enum: 'string',
  binary: 'bytes',
};

export class GrpcTransport implements ITransport {
  readonly name = 'grpc';

  private config: TransportConfig | null = null;
  private schemas: EntitySchema[] = [];
  private middlewares: TransportMiddleware[] = [];
  private ormHandler: OrmHandler | null = null;
  private server: any = null;
  private stats = { requests: 0, errors: 0, startedAt: 0 };

  setHandler(handler: OrmHandler): void { this.ormHandler = handler; }
  use(mw: TransportMiddleware): void { this.middlewares.push(mw); }
  registerEntity(schema: EntitySchema): void { this.schemas.push(schema); }

  // ============================================================
  // Proto generation
  // ============================================================

  /**
   * Generate a complete .proto file from all registered EntitySchemas.
   * One service per entity with CRUD rpcs.
   */
  generateProto(): string {
    const lines: string[] = [
      'syntax = "proto3";',
      '',
      'package mostajs;',
      '',
      '// Auto-generated by @mostajs/net GrpcTransport',
      `// Entities: ${this.schemas.map(s => s.name).join(', ')}`,
      `// Generated: ${new Date().toISOString()}`,
      '',
      '// ── Common types ──',
      '',
      'message Empty {}',
      '',
      'message IdRequest {',
      '  string id = 1;',
      '}',
      '',
      'message FilterRequest {',
      '  string filter = 1;  // JSON filter object',
      '  string sort = 2;    // JSON sort object',
      '  int32 limit = 3;',
      '  int32 skip = 4;',
      '}',
      '',
      'message CountResponse {',
      '  int64 count = 1;',
      '}',
      '',
      'message StatusResponse {',
      '  string status = 1;',
      '  string message = 2;',
      '  string data = 3;  // JSON string',
      '}',
      '',
    ];

    for (const schema of this.schemas) {
      lines.push(`// ── ${schema.name} ──`);
      lines.push('');

      // Message type
      lines.push(`message ${schema.name} {`);
      lines.push('  string id = 1;');
      let fieldNum = 2;
      for (const [fieldName, fieldDef] of Object.entries(schema.fields || {})) {
        const protoType = PROTO_TYPES[(fieldDef as any).type] || 'string';
        lines.push(`  ${protoType} ${fieldName} = ${fieldNum};`);
        fieldNum++;
      }
      lines.push('}');
      lines.push('');

      // List response
      lines.push(`message ${schema.name}List {`);
      lines.push(`  repeated ${schema.name} items = 1;`);
      lines.push('  int64 total = 2;');
      lines.push('}');
      lines.push('');

      // Create/Update request
      lines.push(`message ${schema.name}Input {`);
      lines.push('  string data = 1;  // JSON string');
      lines.push('}');
      lines.push('');

      lines.push(`message ${schema.name}UpdateInput {`);
      lines.push('  string id = 1;');
      lines.push('  string data = 2;  // JSON string');
      lines.push('}');
      lines.push('');

      // Service
      lines.push(`service ${schema.name}Service {`);
      lines.push(`  rpc FindAll (FilterRequest) returns (${schema.name}List);`);
      lines.push(`  rpc FindById (IdRequest) returns (${schema.name});`);
      lines.push(`  rpc Create (${schema.name}Input) returns (${schema.name});`);
      lines.push(`  rpc Update (${schema.name}UpdateInput) returns (${schema.name});`);
      lines.push(`  rpc Delete (IdRequest) returns (StatusResponse);`);
      lines.push(`  rpc Count (FilterRequest) returns (CountResponse);`);
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate service implementations that delegate to the ORM handler.
   */
  generateServiceImplementations(): Record<string, Record<string, (call: any, callback: any) => void>> {
    const services: Record<string, Record<string, (call: any, callback: any) => void>> = {};

    for (const schema of this.schemas) {
      const entity = schema.name;

      services[`${entity}Service`] = {
        FindAll: (call: any, callback: any) => {
          this.handleRpc(entity, 'findAll', call.request, callback);
        },
        FindById: (call: any, callback: any) => {
          this.handleRpc(entity, 'findById', call.request, callback);
        },
        Create: (call: any, callback: any) => {
          this.handleRpc(entity, 'create', call.request, callback);
        },
        Update: (call: any, callback: any) => {
          this.handleRpc(entity, 'update', call.request, callback);
        },
        Delete: (call: any, callback: any) => {
          this.handleRpc(entity, 'delete', call.request, callback);
        },
        Count: (call: any, callback: any) => {
          this.handleRpc(entity, 'count', call.request, callback);
        },
      };
    }

    return services;
  }

  // ============================================================
  // RPC handler
  // ============================================================

  private async handleRpc(entity: string, op: string, request: any, callback: any): Promise<void> {
    this.stats.requests++;

    const ormReq: OrmRequest = { op: op as any, entity };

    switch (op) {
      case 'findAll': {
        if (request.filter) ormReq.filter = JSON.parse(request.filter);
        ormReq.options = {};
        if (request.sort) ormReq.options.sort = JSON.parse(request.sort);
        if (request.limit) ormReq.options.limit = request.limit;
        if (request.skip) ormReq.options.skip = request.skip;
        break;
      }
      case 'findById':
      case 'delete':
        ormReq.id = request.id;
        break;
      case 'create':
        ormReq.data = JSON.parse(request.data);
        break;
      case 'update':
        ormReq.id = request.id;
        ormReq.data = JSON.parse(request.data);
        break;
      case 'count':
        if (request.filter) ormReq.filter = JSON.parse(request.filter);
        break;
    }

    try {
      const ctx: TransportContext = { transport: this.name };

      // Apply middleware chain
      let res: OrmResponse;
      if (this.middlewares.length > 0 && this.ormHandler) {
        let index = 0;
        const handler = this.ormHandler;
        const mws = this.middlewares;
        const next = async (): Promise<OrmResponse> => {
          if (index < mws.length) return mws[index++](ormReq, ctx, next);
          return handler(ormReq, ctx);
        };
        res = await next();
      } else if (this.ormHandler) {
        res = await this.ormHandler(ormReq, ctx);
      } else {
        callback({ code: 13, message: 'ORM handler not initialized' });
        return;
      }

      if (res.status === 'error') {
        this.stats.errors++;
        callback(null, { status: 'error', message: res.error?.message || 'Error', data: JSON.stringify(res.error) });
        return;
      }

      // Format response based on operation
      switch (op) {
        case 'findAll':
          callback(null, {
            items: (Array.isArray(res.data) ? res.data : []).map(item => this.serializeEntity(item)),
            total: res.metadata?.count || (Array.isArray(res.data) ? res.data.length : 0),
          });
          break;
        case 'count':
          callback(null, { count: res.data || 0 });
          break;
        case 'delete':
          callback(null, { status: 'ok', message: 'Deleted', data: JSON.stringify(res.data) });
          break;
        default:
          callback(null, this.serializeEntity(res.data));
          break;
      }
    } catch (err) {
      this.stats.errors++;
      callback({ code: 13, message: err instanceof Error ? err.message : String(err) });
    }
  }

  private serializeEntity(data: any): any {
    if (!data) return {};
    const result: any = {};
    for (const [key, value] of Object.entries(data)) {
      if (value === null || value === undefined) continue;
      if (typeof value === 'object' && !(value instanceof Date)) {
        result[key] = JSON.stringify(value);
      } else if (value instanceof Date) {
        result[key] = value.toISOString();
      } else {
        result[key] = value;
      }
    }
    return result;
  }

  // ============================================================
  // Start / Stop
  // ============================================================

  async start(config: TransportConfig): Promise<void> {
    this.config = config;
    this.stats.startedAt = Date.now();

    // gRPC server is started separately (requires @grpc/grpc-js)
    // The proto and service implementations are available via generateProto() and generateServiceImplementations()
    // Integration with Fastify is done in server.ts
  }

  async stop(): Promise<void> {
    if (this.server) {
      this.server.forceShutdown();
      this.server = null;
    }
    this.config = null;
  }

  getInfo(): TransportInfo {
    return {
      name: this.name,
      status: this.config ? 'running' : 'stopped',
      port: this.config?.port,
      url: ':' + (this.config?.port || 50051),
      entities: this.schemas.map(s => s.name),
      stats: { ...this.stats },
    };
  }

  getProto(): string { return this.generateProto(); }
  getServices(): Record<string, Record<string, Function>> { return this.generateServiceImplementations(); }
}

/** Factory */
export function createTransport(): ITransport {
  return new GrpcTransport();
}
