// TrpcTransport — tRPC transport adapter
// Auto-generates tRPC router from EntitySchemas for TypeScript fullstack
// Author: Dr Hamid MADANI drmdh@msn.com

import type { EntitySchema, OrmRequest, OrmResponse } from '@mostajs/orm';
import type { ITransport, TransportConfig, TransportInfo, TransportMiddleware, TransportContext } from '../core/types.js';

type OrmHandler = (req: OrmRequest, ctx: TransportContext) => Promise<OrmResponse>;

export class TrpcTransport implements ITransport {
  readonly name = 'trpc';

  private config: TransportConfig | null = null;
  private schemas: EntitySchema[] = [];
  private middlewares: TransportMiddleware[] = [];
  private ormHandler: OrmHandler | null = null;
  private stats = { requests: 0, errors: 0, startedAt: 0 };

  setHandler(handler: OrmHandler): void { this.ormHandler = handler; }
  use(mw: TransportMiddleware): void { this.middlewares.push(mw); }
  registerEntity(schema: EntitySchema): void { this.schemas.push(schema); }

  /**
   * Handle a tRPC-style HTTP request.
   * tRPC uses batch HTTP with JSON body.
   * URL pattern: /trpc/{entity}.{operation}
   */
  async handleRequest(path: string, body: any): Promise<any> {
    this.stats.requests++;

    // Parse path: /trpc/User.findAll → entity=User, op=findAll
    const match = path.match(/\/trpc\/(\w+)\.(\w+)/);
    if (!match) {
      return { error: { code: 'BAD_REQUEST', message: 'Invalid path. Use /trpc/{entity}.{operation}' } };
    }

    const [, entityName, op] = match;
    const schema = this.schemas.find(s => s.name === entityName || s.collection === entityName);
    if (!schema) {
      return { error: { code: 'NOT_FOUND', message: `Entity "${entityName}" not found` } };
    }

    const ormReq: OrmRequest = { op: op as any, entity: schema.name };

    // Map tRPC input to OrmRequest
    const input = body?.input || body || {};
    if (input.id) ormReq.id = input.id;
    if (input.filter) ormReq.filter = typeof input.filter === 'string' ? JSON.parse(input.filter) : input.filter;
    if (input.data) ormReq.data = typeof input.data === 'string' ? JSON.parse(input.data) : input.data;
    if (input.sort || input.limit || input.skip) {
      ormReq.options = {};
      if (input.sort) ormReq.options.sort = typeof input.sort === 'string' ? JSON.parse(input.sort) : input.sort;
      if (input.limit) ormReq.options.limit = Number(input.limit);
      if (input.skip) ormReq.options.skip = Number(input.skip);
    }
    if (input.query) (ormReq as any).query = input.query;
    if (input.field) (ormReq as any).field = input.field;
    if (input.value) (ormReq as any).value = input.value;
    if (input.amount) (ormReq as any).amount = Number(input.amount);
    if (input.stages) ormReq.stages = typeof input.stages === 'string' ? JSON.parse(input.stages) : input.stages;

    try {
      const ctx: TransportContext = { transport: this.name };

      let res: OrmResponse;
      if (this.middlewares.length > 0 && this.ormHandler) {
        let index = 0;
        const handler = this.ormHandler;
        const mws = this.middlewares;
        const next = async (): Promise<OrmResponse> => {
          if (index < mws.length) return mws[index++](ormReq, ctx, next);
          return handler(ormReq, ctx);
        };
        res = await next();
      } else if (this.ormHandler) {
        res = await this.ormHandler(ormReq, ctx);
      } else {
        return { error: { code: 'INTERNAL', message: 'ORM handler not initialized' } };
      }

      // tRPC response format
      return { result: { data: res } };
    } catch (err) {
      this.stats.errors++;
      return { error: { code: 'INTERNAL', message: err instanceof Error ? err.message : String(err) } };
    }
  }

  /**
   * Generate TypeScript type definitions for tRPC client.
   */
  generateTypes(): string {
    const lines: string[] = [
      '// Auto-generated by @mostajs/net TrpcTransport',
      '// Types for tRPC client',
      '',
    ];

    for (const schema of this.schemas) {
      const name = schema.name;
      lines.push(`export interface ${name} {`);
      lines.push('  id: string;');
      for (const [field, def] of Object.entries(schema.fields || {})) {
        const tsType = (def as any).type === 'number' || (def as any).type === 'integer' || (def as any).type === 'float' || (def as any).type === 'decimal' ? 'number'
          : (def as any).type === 'boolean' ? 'boolean'
          : (def as any).type === 'date' ? 'Date'
          : (def as any).type === 'json' || (def as any).type === 'array' ? 'any'
          : 'string';
        const optional = (def as any).required ? '' : '?';
        lines.push(`  ${field}${optional}: ${tsType};`);
      }
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * List available procedures (entity.operation pairs).
   */
  listProcedures(): { name: string; type: 'query' | 'mutation'; entity: string; operation: string }[] {
    const procs: any[] = [];
    const queries = ['findAll', 'findById', 'count', 'findOne', 'search'];
    const mutations = ['create', 'update', 'delete', 'upsert', 'deleteMany', 'updateMany'];

    for (const schema of this.schemas) {
      for (const op of queries) {
        procs.push({ name: `${schema.name}.${op}`, type: 'query', entity: schema.name, operation: op });
      }
      for (const op of mutations) {
        procs.push({ name: `${schema.name}.${op}`, type: 'mutation', entity: schema.name, operation: op });
      }
    }
    return procs;
  }

  getPath(): string { return this.config?.path || '/trpc'; }

  async start(config: TransportConfig): Promise<void> {
    this.config = config;
    this.stats.startedAt = Date.now();
  }

  async stop(): Promise<void> { this.config = null; }

  getInfo(): TransportInfo {
    return {
      name: this.name,
      status: this.config ? 'running' : 'stopped',
      url: this.config?.path || '/trpc',
      entities: this.schemas.map(s => s.name),
      stats: { ...this.stats },
    };
  }
}

/** Factory */
export function createTransport(): ITransport {
  return new TrpcTransport();
}
